version: '3.8'

services:
  backend:
    build:
      context: ./ThreeGame
    ports:
      - "8080:8080"
      - "9092:9292"
    volumes:
      - ./ThreeGame/env.properties:/app/env.properties

  frontend:
    build:
      context: ./phaser-JsToAngular-3game
    ports:
      - "4200:80"
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"  # Aggiungi la porta 443 per HTTPS
    volumes:
      - ./phaser-JsToAngular-3game/my-angular-app.conf:/etc/nginx/conf.d/default.conf
      - ./phaser-JsToAngular-3game/dist:/usr/share/nginx/html
      - ./fullchain.pem:/etc/letsencrypt/live/giahck.it/fullchain.pem:ro  # Certificato SSL
      - ./privkey.pem:/etc/letsencrypt/live/giahck.it/privkey.pem:ro
      - ./dhparam.pem:/etc/letsencrypt/live/giahck.it/dhparam.pem:ro
      - ./nginx-logs/access.log:/var/log/nginx/access.log  # Log di accesso
      - ./nginx-logs/error.log:/var/log/nginx/error.log
    depends_on:
      - frontend
      - backend

networks:
  default:
    driver: bridge
